# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - master
    - feature/*
    - release/*

variables:
  MY_VAR: "Test"
  DEV_ORG_LOGIN: "dev_org"
  STAGR_ORG_LOGIN: "stage_org"
  PROD_ORG_LOGIN: "prod_org"
  REGION: "us"

stages:
- stage: BuildStage
  displayName: Build Stage
  jobs:
  - job: Package
    displayName: IICS Package
    timeoutInMinutes: 10
    workspace: 
      clean: all
    steps:
    - script: echo "IICS package command"
      #iics package -z file.zip -w 
- stage: Devdeploymentjob
  displayName: Dev Deployment
  jobs:
  - job: Import
    displayName: Import
    steps:
    - script: echo "IICS import command"
    #iics import --region $(region) --username $(username) --password $(password) --zipFilePath file.zip
  - deployment:
    displayName: Dev Deployment Job
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - bash: echo "This is a Dev deployment job $(MY_VAR)" 
- stage: StageDeployment
  displayName: Stage Deployment
  jobs:
    - deployment: 
      displayName: Stage Deployment Job
      continueOnError: false
      environment: Stage
      strategy:
       runOnce:
        deploy:
          steps:
            - bash: echo "This is a Stage Deployment job"