version: "3.8"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - "Name: Jenkins"
        - "Environment: Dev"
    container_name: Jenkins-container
    ports:
    - "50000:50000"
    - "8080:8080"
    restart: on-failure
    networks:
      - jenkins-network
    volumes:
      - "jenkins-home:/var/jenkins_home"
  nginx:
    image: nginx:1.19.0-alpine
    labels:
      - "Name:Nginx"
      - "Environment:Dev"
    ports:
      - "8181:8181"
    restart: on-failure
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - jenkins
    networks:
      - jenkins-network
    links:
      - "jenkins"
    container_name: Nginx-container
volumes:
  jenkins-home:
networks:
  jenkins-network:
