version: "3.3"
services:
  prometheus:
    build:
      context: .
      # dockerfile: Dockerfile
      labels:
        - "Name:Prometheus"
        - "Environment:Prod"
    ports:
      - "9090:9090"
    container_name: monitoring_prometheus
    expose:
      - 9090
    networks:
      - hostnetwork
    restart: on-failure
    volumes:
       - "prometheus:/prometheus"
       - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - hostnetwork
    depends_on:
      - prometheus
    volumes:
      - "grafana:/var/lib/grafana"
      - "./defaults.ini:/usr/share/grafana/conf/defaults.ini"
    links:
      - "prometheus"
    container_name: monitoring_grafana
  NodeExporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - hostnetwork
    depends_on:
      - prometheus
    links:
      - "prometheus"
    container_name: NodeExporter-container
    restart: on-failure
networks:
  hostnetwork:
volumes:
  prometheus:
  grafana:
