Description: Default Target group for ALB

Parameters:
  SSLCertificateArn:
    Type: String
    Description: "Enter SSL Certificate ARN"
    # Default:
  ALBARN:
    Type: String
    Description: Enter ALB ARN
  DefaultTargetGroupARN:
    Type: String
    Description: Default Target Group ARN.

Resources:
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
       - Type: "redirect"
         RedirectConfig:
           Protocol: "HTTPS"
           Port: "443"
           Host: "#{host}"
           Path: "/#{path}"
           Query: "#{query}"
           StatusCode: "HTTP_301"
      LoadBalancerArn: !Ref 'ALBARN'
      Port: 80
      Protocol: "HTTP"

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref 'SSLCertificateArn'
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref 'DefaultTargetGroupARN'
      LoadBalancerArn: !Ref 'ALBARN'
      Port: 443
      Protocol: "HTTPS"

Outputs:
  HttpListenerARN:
    Value: !Ref 'HttpListener'
  HttpsListenerARN:
    Value: !Ref 'HttpsListener'
