Description: Default Target group for ALB

Parameters:
  HttpListenerARN:
    Type: String
    Description: Enter HTTP Listener ARN
  HttpsListenerARN:
    Type: String
    Description: Enter HTTPS Listener ARN
  WebServerTargetGroupARN:
    Type: String
    Description: Default Target Group ARN.
  WebSocketTargetGrouptARN:
    Type: String
    Description: Default Target Group ARN.
  WebDomains:
    Type: CommaDelimitedList
    Description: enter Domain names in coma separated.
  SocketDomain:
    Type: String
    Description: enter Socket Domain name
  # Priority:
  #   Type: Number
  #   Description: Enter the rule Priority

Resources:
  WebServerHttpsListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref 'HttpsListenerARN'
      Actions:
        - Type: forward
          TargetGroupArn: !Ref 'WebServerTargetGroupARN'
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - 'gritit-survey-preprod.qburst.build'
              - 'gritit-swagger-preprod.qburst.build'
              - 'gritit-api-preprod.qburst.build'
              - 'gritit-backend-preprod.qburst.build'
              # - !Select [ 0, !Ref 'WebDomains' ]
              # - !Select [ 1, !Ref 'WebDomains' ]
              # - !Select [ 2, !Ref 'WebDomains' ]
              # - !Select [ 3, !Ref 'WebDomains' ]
      Priority: 11

  WebSocketHttpsListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref 'HttpsListenerARN'
      Actions:
        - Type: forward
          TargetGroupArn: !Ref 'WebServerTargetGroupARN'
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref 'SocketDomain'
      Priority: 10

  HttpListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref 'HttpListenerARN'
      Actions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - 'gritit-survey-preprod.qburst.build'
              - 'gritit-swagger-preprod.qburst.build'
              - 'gritit-api-preprod.qburst.build'
              - 'gritit-backend-preprod.qburst.build'
              - 'gritit-socket-preprod.qburst.build'
      Priority: 10
