Description: Target Groups

Parameters:
  HealthCheckPath:
    Description: Health check path
    Type: String
    Default: /index.html
  HealthCheckPort:
    Type: String
    Description: health check port
    Default: 80
  TargetGroupName:
    Type: String
    Default: Sample
  Port:
    Type: Number
    Default: 80
  Environment:
    Type: String
    Default: Dev
  VPCID:
    Description: VPC ID
    Type: "AWS::EC2::VPC::Id"
  AppName:
    Description: Enter The AppName
    Type: String
    Default: Sample

Resources:

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 15
      HealthCheckPath: !Ref 'HealthCheckPath'
      HealthCheckPort: !Ref 'HealthCheckPort'
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      Name: !Ref 'TargetGroupName'
      Port: !Ref 'Port'
      Protocol: HTTP
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-${AppName}-TargetGroup
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: false
        - Key: load_balancing.algorithm.type
          Value: round_robin
      # Targets:
      #   - TargetDescription
      # TargetType: String
      UnhealthyThresholdCount: 2
      VpcId: !Ref 'VPCID'


Outputs:
  TargetGroupARN:
    Value: !Ref 'TargetGroup'
  TargetGroupName:
    Value: !GetAtt 'TargetGroup.TargetGroupName'
  TargetGroupFullName:
    Value: !GetAtt 'TargetGroup.TargetGroupFullName'
