AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates Application Load balancer and ALB Security Groups.

Resources:

  ApplicationLoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the public facing load balancer
      GroupName: !Join ["-",[!ImportValue 'Environment', "ALB", "SG"]]
      VpcId: !Join ["-"[!ImportValue 'Environment', VPC]]
      SecurityGroupIngress:
          # Allow access to ALB from anywhere on the internet
          - CidrIp: 0.0.0.0/0
            IpProtocol: -1
          - CidrIpv6: ::/0
            IpProtocol: -1
      Tags:
        - Key: Name
          Value: !Join ["-",[!ImportValue 'Environment', "ALB", "SG"]]
        - Key: VPC
          Value: !Join ["-"[!ImportValue 'Environment', VPC]]


#LoadBalancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join ["-",[!ImportValue "Project-Name", !ImportValue "Environment", "ALB"]]
      IpAddressType: dualstack
      LoadBalancerAttributes:
          # - Key: deletion_protection.enabled
          #   Value: true
          - Key: idle_timeout.timeout_seconds
            Value: 600
          # - Key: access_logs.s3.enabled
          #   Value: true
          # - Key: access_logs.s3.bucket
          #   Value: <create bucket for load balancer>

      Scheme: internet-facing
      SecurityGroups:
        - !Ref 'ApplicationLoadBalancerSG'
      Subnets:
        - !Join ["-"[!ImportValue 'Environment', PublicSubnet1]]
        - !Join ["-"[!ImportValue 'Environment', PublicSubnet2]]
      Type: application
      Tags:
        - Key: Name
          Value: !Join ["-"[!ImportValue 'Environment', VPC]]
        - Key: Environment
          Value: !ImportValue 'Environment'

Outputs:
  ALBSG:
    Description: ALB Security Group
    Value: !Ref 'ApplicationLoadBalancerSG'
    Export:
      Name: ALBSG
  ALB:
    Description: Application Load balancer
    Value: !Ref 'ApplicationLoadBalancer'
    Export:
      Name: ALB
  ALBDNS:
    Description: ALB DNS
    Value: !GetAtt 'ApplicationLoadBalancer.DNSName'
    Export:
      Name: AlbDNS
